Metrics/LineLength:
  Max: 130

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/mixtape/app.rb'
    - 'lib/mixtape/changes_processor.rb'
    - 'lib/mixtape/exception.rb'
    - 'lib/mixtape/input_index.rb'

Metrics/BlockLength:
  Max: 130
